# Generated by Django 5.1.1 on 2024-10-10 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_deliciousmenu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu_Board_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('item_category', models.CharField(choices=[('veg', 'veg'), ('non_veg', 'non_veg')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TodayDinnerMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('items', models.ManyToManyField(related_name='today_dinner_menu', to='home.menu_board_items')),
            ],
        ),
        migrations.CreateModel(
            name='TodayLunchMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('items', models.ManyToManyField(related_name='today_lunch_menu', to='home.menu_board_items')),
            ],
        ),
        migrations.DeleteModel(
            name='TodayMenu',
        ),
    ]
