# Generated by Django 5.1.1 on 2024-10-10 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_image', models.ImageField(upload_to='items/')),
                ('item_name', models.CharField(max_length=100)),
                ('item_description', models.TextField()),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.RemoveField(
            model_name='todaymenu',
            name='dinner_menu',
        ),
        migrations.RemoveField(
            model_name='todaymenu',
            name='lunch_menu',
        ),
        migrations.RenameField(
            model_name='scanner',
            old_name='scanner',
            new_name='scanner_image',
        ),
        migrations.CreateModel(
            name='DinnerMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.ManyToManyField(related_name='dinner_menus', to='home.item')),
            ],
        ),
        migrations.CreateModel(
            name='LunchMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.ManyToManyField(related_name='lunch_menus', to='home.item')),
            ],
        ),
        migrations.DeleteModel(
            name='DinnerMenuItem',
        ),
        migrations.AddField(
            model_name='todaymenu',
            name='dinner_menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='today_menus', to='home.dinnermenu'),
        ),
        migrations.DeleteModel(
            name='LunchMenuItem',
        ),
        migrations.AddField(
            model_name='todaymenu',
            name='lunch_menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='today_menus', to='home.lunchmenu'),
        ),
    ]
