# Generated by Django 5.1.1 on 2024-10-14 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivery_address_cart',
            new_name='delivery_address',
        ),
    ]
