# Generated by Django 5.1.1 on 2024-10-14 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_delivery_address_cart_order_delivery_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_address',
        ),
    ]
