# Generated by Django 5.1.1 on 2024-10-10 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_dinnermenu_created_at_lunchmenu_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliciousMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('items', models.ManyToManyField(related_name='delicious_menus', to='home.item')),
            ],
        ),
    ]
