# Generated by Django 5.1.1 on 2024-10-10 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_menu_board_items_todaydinnermenu_todaylunchmenu_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu_board_items',
            name='item_category',
        ),
        migrations.AddField(
            model_name='todaydinnermenu',
            name='item_category',
            field=models.CharField(choices=[('veg', 'veg'), ('non_veg', 'non_veg')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todaylunchmenu',
            name='item_category',
            field=models.CharField(choices=[('veg', 'veg'), ('non_veg', 'non_veg')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
