# Generated by Django 5.1.1 on 2024-10-15 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_deliveryaddress_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_otp',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
