# Generated by Django 5.1.1 on 2024-10-12 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_menu_board_items_item_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='todaydinnermenu',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todaylunchmenu',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
