# Generated by Django 5.1.1 on 2024-10-16 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_order_delivery_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='expiration_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
