# Generated by Django 5.1.1 on 2024-10-18 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_order_expiration_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryaddress',
            name='address_line1',
            field=models.CharField(choices=[('IIIT', 'IIIT'), ('STPI', 'STPI'), ('KIIT', 'KIIT')], default='IIIT', max_length=255),
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='city',
            field=models.CharField(choices=[('Bhubaneswar', 'Bhubaneswar')], default='Bhubaneswar', max_length=100),
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='phone_number',
            field=models.CharField(default='XXXXXXXXXX', max_length=10),
        ),
    ]
