# Generated by Django 5.1.1 on 2024-10-13 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_order_is_completed_remove_order_item_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='finalamount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
