# Generated by Django 5.1.1 on 2024-11-14 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_deliveryaddress_address_line1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todaylunchmenu',
            name='items',
        ),
        migrations.CreateModel(
            name='WeeklyMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=20)),
                ('meal_type', models.CharField(choices=[('Lunch', 'Lunch'), ('Dinner', 'Dinner')], max_length=20)),
                ('item_category', models.CharField(choices=[('veg', 'veg'), ('non_veg', 'non_veg')], max_length=100)),
                ('price', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('items', models.ManyToManyField(related_name='weekly_menu', to='home.menu_board_items')),
            ],
        ),
        migrations.DeleteModel(
            name='TodayDinnerMenu',
        ),
        migrations.DeleteModel(
            name='TodayLunchMenu',
        ),
    ]
